save_dir: ./saved_models
save_name: ACS_HAR_0.1
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 120
num_train_iter: 120
num_eval_iter: 1
num_labels: 0.1
seed: 4
batch_size: 32
eval_batch_size: 120
hard_label: True
T: 0.5
ulb_loss_ratio: 0.
ent_loss_ratio: 0.05
uratio: 7
ema_m: 0.999
optim: AdamW
lr: 0.0001
momentum: 0.9
weight_decay: 0.0003
amp: False
net:   ACS_HAR
net_from_name: False
mlp_ratio: 2.
in_chans: 9
embed_dim: 40
depths: [1, 2, 8, 2]
feature_dim: 128
hidden_num: 64
drop_path_rate: 0.
act_layer: GELU
n_div: 4
data_dir: ./data
dataset: uci
train_sampler: RandomSampler
num_classes: 6
num_workers: 1
alg: ACS-HAR
avg: 128
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:11126
dist_backend: nccl
gpu: 0
