save_dir: ./saved_models
save_name: fullysupervised_pamap_
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 120
num_train_iter: 120
num_eval_iter: 1
num_labels: 0.01 
batch_size: 32
eval_batch_size: 120
ema_m: 0.999
optim: AdamW
lr: 0.0001
momentum: 0.9
weight_decay: 0.0003
amp: False
net: FasterNet
net_from_name: False
mlp_ratio: 2.
in_chans: 52
embed_dim: 40
depths: [1, 2, 8, 2]
feature_dim: 128
hidden_num: 64
drop_path_rate: 0.
act_layer: GELU
data_dir: ./data
dataset: pamap
train_sampler: RandomSampler
num_classes: 12
num_workers: 1
alg: fullysupervised
seed: 2
world_size: 1
n_div: 4
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10047
dist_backend: nccl
gpu: 1